name: Docker Image CI

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
  publish:
     runs-on: ubuntu-latest
     needs: build 
     steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kingscourt/staging:latest

  deploy:
    runs-on: ubuntu-latest
    needs: publish
    steps:

    - name: stop and remove docker image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SECRET_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: docker stop kingscourtstaging && docker rm kingscourtstaging

    - name: deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SECRET_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: docker pull kingscourt/staging:latest && docker run -e conn_string_staging=${{ secrets.CONN_STRING }} -d --name kingscourtstaging -p 420:80 kingscourt/staging:latest
